#!/bin/bash
# Copyright 2024 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

#
# WARNING: This file is generated by Terraform.  Any direct edits will be overwritten when applying Terraform changes.

. ./scripts/dev/base_env.sh

project_id="${GCP_PROJECT}"
region="${GCP_REGION}"
service_name="${SERVICE_NAME}"
local_service_port="${LOCAL_SERVICE_PORT}"

gcloud run services proxy "${service_name}" --project "${project_id}" --region "${region}" --port ${local_service_port}
