[dependency-groups]
dev = [
  "ipykernel>=7.0.1",
  "pre-commit>=4.5.1",
  "pytest>=9.0.2",
  "pytest-asyncio>=1.3.0"
]

[project]
name = "adk-mcp-oauth"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12,<3.13"
dependencies = [
  "agent-starter-pack>=0.38.0",
  "fastapi>=0.132.0",
  "google-adk[eval]>=1.18",
  "google-auth>=2.41.1",
  "google-auth-oauthlib>=1.2.2",
  "google-cloud-aiplatform>=1.138.0",
  "google-cloud-logging>=3.13.0",
  "google-genai>=1.43.0",
  "pip>=25.2",
  "pre-commit>=4.5.1",
  "pydantic>=2.12.5",
  "python-dotenv>=1.2.1",
  "ruff>=0.15.2"
]

[project.optional-dependencies]
lint = [
  "codespell>=2.4.1",
  "ruff>=0.15.2",
  "ty>=0.0.18"
]

[tool.setuptools.packages.find]
where = ["src"]

[[tool.uv.index]]
name = "pypi"
url = "https://pypi.org/simple"
default = true
