# Copyright 2025 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

#
# WARNING: This file is generated by Terraform.  Any direct edits will be overwritten when applying Terraform changes.

import toml
import os
import sys
from dotenv import load_dotenv
from vertexai.preview.reasoning_engines import AdkApp
import google.cloud.logging
from datetime import datetime, timezone
from google.cloud import firestore
import uuid
from google.adk.events import Event, EventActions
import time

sys.path.append(os.path.dirname(os.path.abspath(__file__)))

from config import plugins


def get_dependencies_from_toml(file_path: str) -> set[str]:
    """
    Reads a pyproject.toml file and extracts the dependencies listed under
    the [project] section.

    Args:
        file_path: Path to the pyproject.toml file.

    Returns:
        A set of dependency strings.
    """
    with open(file_path, "r") as f:
        data = toml.load(f)
        dependencies = data.get("project", {}).get("dependencies", [])
        return set(dependencies)


def format_dependencies_list(raw_dependencies: list[str]) -> list[str]:
    """
    Parses a list of raw dependency strings and converts each line
    into a clean, formatted string for a Python list.

    Args:
        raw_dependencies: A list of strings, where each string is a dependency line.

    Returns:
        A list of formatted dependency strings.
    """
    formatted_list = []

    for dep_line in raw_dependencies:
        # Strip whitespace, quotes, and comments
        dep = dep_line.strip().strip('"')
        if not dep or dep.startswith('#'):
            continue

        # Handle special git-based dependencies and convert to local path format
        if "git+ssh" in dep:
            pkg_name = dep.split("@")[0]
            formatted_list.append(f'{pkg_name.strip()} @ file:///code/{pkg_name.strip()}')
        elif "file://" in dep:
            pkg_name = dep.split("@")[0]
            formatted_list.append(f'{pkg_name.strip()} @ file:///code/{pkg_name.strip()}')
        # Handle all other standard packages
        else:
            # Clean up the string to remove parentheses and spaces
            cleaned_dep = dep.replace("(", "").replace(")", "").replace(" ", "")
            formatted_list.append(f'{cleaned_dep}')

    return formatted_list

def get_folder_or_gitssh_dependencies_from_toml(file_path: str) -> set[str]:
    """
    Reads a pyproject.toml file and extracts the dependencies listed under
    the [project] section.

    Args:
        file_path: Path to the pyproject.toml file.

    Returns:
        A set of dependency strings.
    """
    dependencies: set = set()
    with open(file_path, "r") as f:
        data = toml.load(f)
        dependencies = data.get("project", {}).get("dependencies", [])
        dependencies = set(dependencies)

    formatted_set: set = set()

    for dep_line in dependencies:
        # Strip whitespace, quotes, and comments
        dep = dep_line.strip().strip('"')
        if not dep or dep.startswith('#'):
            continue

        # Handle special git-based dependencies and convert to local path format
        if "git+ssh" in dep:
            pkg_name = dep.split("@")[0]
            formatted_set.add(f'{pkg_name.strip()}')
        elif "file://" in dep:
            pkg_name = dep.split("@")[0]
            formatted_set.add(f'{pkg_name.strip()}')
        # Handle all other standard packages
        else:
            # Do nothing.
            pass

    return formatted_set



class App:
    """Wrapper class for Agent Engine deployment"""

    agent_framework = "google-adk"

    def __init__(self):
        # Don't initialize anything here that can't be pickled
        # We'll do actual initialization in set_up()
        load_dotenv()

        self.AGENT_NAME = os.environ["AGENT_NAME"]
        self.STAGING_BUCKET_URI = os.environ["STAGING_BUCKET_URI"]

        self.HTTP_PROXY = ""
        self.HTTPS_PROXY = ""
        self.NO_PROXY = ""
        self.SSL_CA_BUNDLE = ""

        # Store shared secrets

        # Store authorization IDs
        self.AUTH_ID = os.environ["AUTH_ID"]

        # Store input environment variables
        self.ADK_CAPTURE_MESSAGE_CONTENT_IN_SPANS = os.environ["ADK_CAPTURE_MESSAGE_CONTENT_IN_SPANS"]
        self.AGENT_CARD_BUCKET_URI = os.environ["AGENT_CARD_BUCKET_URI"]
        self.GOOGLE_CLOUD_AGENT_ENGINE_ENABLE_TELEMETRY = os.environ["GOOGLE_CLOUD_AGENT_ENGINE_ENABLE_TELEMETRY"]
        self.GOOGLE_CLOUD_LOCATION = os.environ["GOOGLE_CLOUD_LOCATION"]
        self.GOOGLE_CLOUD_PROJECT = os.environ["GOOGLE_CLOUD_PROJECT"]
        self.OTEL_INSTRUMENTATION_GENAI_CAPTURE_MESSAGE_CONTENT = os.environ["OTEL_INSTRUMENTATION_GENAI_CAPTURE_MESSAGE_CONTENT"]
        self.OTEL_PYTHON_LOGGING_AUTO_INSTRUMENTATION_ENABLED = os.environ["OTEL_PYTHON_LOGGING_AUTO_INSTRUMENTATION_ENABLED"]
        self.OTEL_SERVICE_NAME = os.environ["OTEL_SERVICE_NAME"]

        # Store parameter environment variables
        self.AGENT_NAME = os.environ["AGENT_NAME"]
        self.GCP_PROJECT = os.environ["GCP_PROJECT"]
        self.GCP_REGION = os.environ["GCP_REGION"]
        self.PHOENIX_COLLECTION_ENDPOINT = os.environ["PHOENIX_COLLECTION_ENDPOINT"]
        self.SERVICE_ACCOUNT_EMAIL = os.environ["SERVICE_ACCOUNT_EMAIL"]
        self.SERVICE_DESC = os.environ["SERVICE_DESC"]
        self.SERVICE_NAME = os.environ["SERVICE_NAME"]
        self.SERVICE_SLUG = os.environ["SERVICE_SLUG"]
        self.STAGING_BUCKET_URI = os.environ["STAGING_BUCKET_URI"]

        print(f"self.AGENT_NAME: {self.AGENT_NAME}")
        print(f"self.STAGING_BUCKET_URI: {self.STAGING_BUCKET_URI}")

    def set_up(self):
        """
        Set up method called by AgentSpace after unpickling.
        All initialization that involves non-picklable objects goes here.
        """

        os.environ["AGENT_NAME"] = self.AGENT_NAME
        os.environ["STAGING_BUCKET_URI"] = self.STAGING_BUCKET_URI

        # TODO: remove after testing.
        """ os.environ["HTTP_PROXY"] = self.HTTP_PROXY
        os.environ["HTTPS_PROXY"] = self.HTTPS_PROXY
        os.environ["NO_PROXY"] = self.NO_PROXY

        os.environ["GRPC_DEFAULT_SSL_ROOTS_FILE_PATH"] = self.SSL_CA_BUNDLE
        os.environ["HTTPLIB2_CA_CERTS"] = self.SSL_CA_BUNDLE
        os.environ["REQUESTS_CA_BUNDLE"] = self.SSL_CA_BUNDLE
        os.environ["SSL_CERT_FILE"] = self.SSL_CA_BUNDLE """

        # Set secret environment variables in ADK runtime.
        # Set authorization IDs environment variables in ADK runtime.
        os.environ["AUTH_ID"] = self.AUTH_ID
        # Set input environment variables in ADK runtime.
        os.environ["ADK_CAPTURE_MESSAGE_CONTENT_IN_SPANS"] = self.ADK_CAPTURE_MESSAGE_CONTENT_IN_SPANS
        os.environ["AGENT_CARD_BUCKET_URI"] = self.AGENT_CARD_BUCKET_URI
        os.environ["GOOGLE_CLOUD_AGENT_ENGINE_ENABLE_TELEMETRY"] = self.GOOGLE_CLOUD_AGENT_ENGINE_ENABLE_TELEMETRY
        os.environ["GOOGLE_CLOUD_LOCATION"] = self.GOOGLE_CLOUD_LOCATION
        os.environ["GOOGLE_CLOUD_PROJECT"] = self.GOOGLE_CLOUD_PROJECT
        os.environ["OTEL_INSTRUMENTATION_GENAI_CAPTURE_MESSAGE_CONTENT"] = self.OTEL_INSTRUMENTATION_GENAI_CAPTURE_MESSAGE_CONTENT
        os.environ["OTEL_PYTHON_LOGGING_AUTO_INSTRUMENTATION_ENABLED"] = self.OTEL_PYTHON_LOGGING_AUTO_INSTRUMENTATION_ENABLED
        os.environ["OTEL_SERVICE_NAME"] = self.OTEL_SERVICE_NAME
        # Set parameter environment variables in ADK runtime.
        os.environ["AGENT_NAME"] = self.AGENT_NAME
        os.environ["GCP_PROJECT"] = self.GCP_PROJECT
        os.environ["GCP_REGION"] = self.GCP_REGION
        os.environ["PHOENIX_COLLECTION_ENDPOINT"] = self.PHOENIX_COLLECTION_ENDPOINT
        os.environ["SERVICE_ACCOUNT_EMAIL"] = self.SERVICE_ACCOUNT_EMAIL
        os.environ["SERVICE_DESC"] = self.SERVICE_DESC
        os.environ["SERVICE_NAME"] = self.SERVICE_NAME
        os.environ["SERVICE_SLUG"] = self.SERVICE_SLUG
        os.environ["STAGING_BUCKET_URI"] = self.STAGING_BUCKET_URI

        print(f"os.environ[\"STAGING_BUCKET_URI\"]: {os.environ['STAGING_BUCKET_URI']}")

        # Initialize Cloud Logging
        self.logging_client = google.cloud.logging.Client(project=self.GCP_PROJECT)
        self.logger = self.logging_client.logger(
            name="running_agent_sessions",
            resource=google.cloud.logging.Resource(
                type="aiplatform.googleapis.com/ReasoningEngine",
                labels={
                    "location": self.GCP_REGION,
                    "resource_container": self.GCP_PROJECT,
                    "reasoning_engine_id": os.environ.get("GOOGLE_CLOUD_AGENT_ENGINE_ID", ""),
                },
            ),
        )

        # Initialize Firestore for persistent session trace mapping
        try:
            self.db = firestore.Client(project=self.GCP_PROJECT)
            self.traces_collection = self.db.collection('session_traces')
        except Exception as e:
            # Fallback to in-memory storage if Firestore is not available
            self.logger.log_struct(
                {
                    "event_type": "firestore_init_failed",
                    "error": str(e),
                    "message": "Falling back to in-memory session trace storage",
                    "timestamp": datetime.now(timezone.utc).isoformat(),
                },
                severity="WARNING"
            )
            self.db = None
            self.traces_collection = None

        # Import and recreate the agent here to avoid pickling issues
        from agent import root_agent

        # Create the agent fresh in the deployed environment
        running_agent = root_agent

        # Prepare environment variables for ADK app
        additional_vars = {}

        # Set secret environment variables in ADK runtime.
        # Set authorization IDs environment variables in ADK runtime.
        additional_vars["AUTH_ID"] = self.AUTH_ID
        # Set input environment variables in ADK runtime.
        additional_vars["ADK_CAPTURE_MESSAGE_CONTENT_IN_SPANS"] = self.ADK_CAPTURE_MESSAGE_CONTENT_IN_SPANS
        additional_vars["AGENT_CARD_BUCKET_URI"] = self.AGENT_CARD_BUCKET_URI
        additional_vars["GOOGLE_CLOUD_AGENT_ENGINE_ENABLE_TELEMETRY"] = self.GOOGLE_CLOUD_AGENT_ENGINE_ENABLE_TELEMETRY
        additional_vars["GOOGLE_CLOUD_LOCATION"] = self.GOOGLE_CLOUD_LOCATION
        additional_vars["GOOGLE_CLOUD_PROJECT"] = self.GOOGLE_CLOUD_PROJECT
        additional_vars["OTEL_INSTRUMENTATION_GENAI_CAPTURE_MESSAGE_CONTENT"] = self.OTEL_INSTRUMENTATION_GENAI_CAPTURE_MESSAGE_CONTENT
        additional_vars["OTEL_PYTHON_LOGGING_AUTO_INSTRUMENTATION_ENABLED"] = self.OTEL_PYTHON_LOGGING_AUTO_INSTRUMENTATION_ENABLED
        additional_vars["OTEL_SERVICE_NAME"] = self.OTEL_SERVICE_NAME
        # Set parameter environment variables in ADK runtime.
        additional_vars["AGENT_NAME"] = self.AGENT_NAME
        additional_vars["GCP_PROJECT"] = self.GCP_PROJECT
        additional_vars["GCP_REGION"] = self.GCP_REGION
        additional_vars["PHOENIX_COLLECTION_ENDPOINT"] = self.PHOENIX_COLLECTION_ENDPOINT
        additional_vars["SERVICE_ACCOUNT_EMAIL"] = self.SERVICE_ACCOUNT_EMAIL
        additional_vars["SERVICE_DESC"] = self.SERVICE_DESC
        additional_vars["SERVICE_NAME"] = self.SERVICE_NAME
        additional_vars["SERVICE_SLUG"] = self.SERVICE_SLUG
        additional_vars["STAGING_BUCKET_URI"] = self.STAGING_BUCKET_URI

        additional_vars["HTTP_PROXY"] = self.HTTP_PROXY
        additional_vars["HTTPS_PROXY"] = self.HTTPS_PROXY
        additional_vars["NO_PROXY"] = self.NO_PROXY

        additional_vars["GRPC_DEFAULT_SSL_ROOTS_FILE_PATH"] = self.SSL_CA_BUNDLE
        additional_vars["HTTPLIB2_CA_CERTS"] = self.SSL_CA_BUNDLE
        additional_vars["REQUESTS_CA_BUNDLE"] = self.SSL_CA_BUNDLE
        additional_vars["SSL_CERT_FILE"] = self.SSL_CA_BUNDLE

        # Initialize the ADK app with environment variables
        self.app = AdkApp(
            agent=running_agent,
            env_vars=additional_vars,
            plugins = plugins.active_adk_plugins,
        )

        # Keep track of active sessions and their trace IDs (in-memory fallback)
        self.session_traces = {}

    def get_trace_id(self):
        """Get the current trace ID from the environment or headers."""
        # Try to get trace from environment (set by Google Cloud)
        trace_header = os.environ.get("X_CLOUD_TRACE_CONTEXT", "")
        if trace_header:
            # Parse the trace header format: TRACE_ID/SPAN_ID;o=TRACE_TRUE
            trace_id = trace_header.split("/")[0]
            return f"projects/{self.GCP_PROJECT}/traces/{trace_id}"

        # Fallback: generate a unique trace ID
        return f"projects/{self.GCP_PROJECT}/traces/{uuid.uuid4().hex}"

    def get_session_trace(self, session_id):
        """Get or create trace ID for a session."""
        if not session_id:
            return self.get_trace_id()

        # Try Firestore first if available
        if self.traces_collection:
            try:
                doc = self.traces_collection.document(session_id).get()
                if doc.exists:
                    return doc.to_dict().get('trace_id')

                # Create new trace ID and store it
                trace_id = self.get_trace_id()
                self.traces_collection.document(session_id).set({
                    'trace_id': trace_id,
                    'created_at': datetime.now(timezone.utc)
                })
                return trace_id
            except Exception as e:
                self.logger.log_struct(
                    {
                        "event_type": "firestore_error",
                        "error": str(e),
                        "session_id": session_id,
                        "timestamp": datetime.now(timezone.utc).isoformat(),
                    },
                    severity="WARNING"
                )

        # Fallback to in-memory storage
        if session_id in self.session_traces:
            return self.session_traces[session_id]

        trace_id = self.get_trace_id()
        self.session_traces[session_id] = trace_id
        return trace_id

    def log_session_event(self, event_type, session_id, user_id, message="", metadata=None):
        """Log session-related events with trace correlation."""
        trace_id = self.get_session_trace(session_id)

        log_entry = {
            "event_type": event_type,
            "session_id": session_id or "no_session",
            "user_id": user_id or "unknown",
            "message": message,
            "timestamp": datetime.now(timezone.utc).isoformat(),
        }

        if metadata:
            log_entry["metadata"] = metadata

        # Log with trace ID - ensure all label values are strings
        self.logger.log_struct(
            log_entry,
            severity="INFO",
            trace=trace_id,
            labels={
                "session_id": str(session_id) if session_id else "no_session",
                "user_id": str(user_id) if user_id else "unknown",
                "event_type": str(event_type),
            }
        )

        return trace_id

    def create_session(self, **kw_args):
        """Create session with logging."""
        user_id = kw_args.get("user_id", "unknown")

        # Log input parameters
        self.logger.log_struct(
            {
                "event_type": "create_session_called",
                "user_id": user_id,
                "raw_kwargs": str(kw_args),
                "timestamp": datetime.now(timezone.utc).isoformat(),
            },
            severity="INFO"
        )

        # Create the session
        result = self.app.create_session(**kw_args)

        # Log the raw result type
        self.logger.log_struct(
            {
                "event_type": "create_session_result",
                "result_type": type(result).__name__,
                "has_id": hasattr(result, 'id'),
                "timestamp": datetime.now(timezone.utc).isoformat(),
            },
            severity="DEBUG"
        )

        # Handle the actual ADK Session object
        session_id = None
        serializable_result = {}

        if hasattr(result, 'id'):
            # It's an ADK Session object
            session_id = result.id
            serializable_result = {
                "output": {
                    "id": session_id,
                    "userId": user_id,
                    "appName": getattr(result, 'app_name', None),
                    "state": getattr(result, 'state', {}),
                    "lastUpdateTime": getattr(result, 'last_update_time', None),
                    "events": getattr(result, 'events', [])
                }
            }
        else:
            # It might already be in the expected format
            if isinstance(result, dict):
                session_id = result.get("id") or result.get("output", {}).get("id")
                serializable_result = {"output": result} if "output" not in result else result
            else:
                # Fallback - try to extract whatever we can
                serializable_result = {"output": {"id": str(result), "userId": user_id}}
                session_id = str(result)

        # Log session creation
        trace_id = self.log_session_event(
            event_type="session_created",
            session_id=session_id,
            user_id=user_id,
            message=f"Session created for user {user_id}",
            metadata={
                "session_id": session_id,
                "app_name": serializable_result.get("output", {}).get("appName")
            }
        )

        # Add trace_id to the output
        if "output" in serializable_result:
            serializable_result["output"]["trace_id"] = trace_id

        # Log successful session creation details
        self.logger.log_struct(
            {
                "event_type": "session_details",
                "session_id": session_id or "unknown",
                "user_id": user_id,
                "app_name": serializable_result.get("output", {}).get("appName"),
                "timestamp": datetime.now(timezone.utc).isoformat(),
            },
            severity="INFO",
            trace=trace_id,
            labels={
                "session_id": str(session_id) if session_id else "unknown",
                "user_id": str(user_id),
                "event_type": "session_details",
            }
        )

        return serializable_result

    def delete_session(self, **kw_args):
        """Delete session with logging."""
        session_id = kw_args.get("session_id")
        user_id = kw_args.get("user_id", "unknown")

        # Log session deletion
        self.log_session_event(
            event_type="session_deleted",
            session_id=session_id,
            user_id=user_id,
            message=f"Session {session_id} deleted"
        )

        # Clean up trace mapping
        if session_id in self.session_traces:
            del self.session_traces[session_id]

        # Clean up from Firestore if available
        if self.traces_collection:
            try:
                self.traces_collection.document(session_id).delete()
            except Exception as e:
                self.logger.log_struct(
                    {
                        "event_type": "firestore_delete_error",
                        "error": str(e),
                        "session_id": session_id,
                        "timestamp": datetime.now(timezone.utc).isoformat(),
                    },
                    severity="WARNING"
                )

        return self.app.delete_session(**kw_args)

    def list_sessions(self, **kw_args):
        return self.app.list_sessions(**kw_args)

    def get_session(self, **kw_args):
        return self.app.get_session(**kw_args)

    def streaming_agent_run_with_events(self, **kw_args):
        """Handle streaming requests with logging."""
        session_id = kw_args.get("session_id")
        user_id = kw_args.get("user_id", "unknown")
        message = kw_args.get("message", "")

        # Log query start
        self.log_session_event(
            event_type="query_started",
            session_id=session_id,
            user_id=user_id,
            message=f"Query: {message[:100]}...",  # Log first 100 chars
            metadata={"full_message": message}
        )

        try:
            # Run the actual streaming
            for event in self.app.streaming_agent_run_with_events(**kw_args):
                yield event

            # Log query completion
            self.log_session_event(
                event_type="query_completed",
                session_id=session_id,
                user_id=user_id,
                message="Query completed successfully"
            )
        except Exception as e:
            # Log query error
            self.log_session_event(
                event_type="query_error",
                session_id=session_id,
                user_id=user_id,
                message=f"Query failed: {str(e)}",
                metadata={"error": str(e)}
            )
            raise

    async def stream_query(self, **kw_args):
        """Stream query with detailed logging."""

        # Debug log to see what's actually being passed
        self.logger.log_struct(
            {
                "event_type": "debug_input",
                "raw_kwargs": str(kw_args),
                "kwargs_keys": list(kw_args.keys()),
                "timestamp": datetime.now(timezone.utc).isoformat(),
            },
            severity="DEBUG"
        )

        # Handle both possible input structures
        # Option 1: Parameters are nested under 'input'
        if "input" in kw_args and isinstance(kw_args["input"], dict):
            input_data = kw_args["input"]
            session_id = input_data.get("session_id")
            user_id = input_data.get("user_id", "unknown")
            message = input_data.get("message", "")
            ui_oauth_token = input_data.get("ui_oauth_token", "unset")
        # Option 2: Parameters are directly in kw_args
        else:
            session_id = kw_args.get("session_id")
            user_id = kw_args.get("user_id", "unknown")
            message = kw_args.get("message", "")
            ui_oauth_token = kw_args.get("ui_oauth_token", "unset")
            # Create input_data for ADK
            input_data = {
                "session_id": session_id,
                "user_id": user_id,
                "message": message,
                "ui_oauth_token": ui_oauth_token
            }

        # Fetch session_service
        state_changes = {
            "ui_oauth_token": ui_oauth_token,
        }
        actions_with_update = EventActions(state_delta=state_changes)
        current_time = time.time()
        system_event = Event(
            invocation_id="inv_login_update",
            author="system",
            actions=actions_with_update,
            timestamp=current_time
            # content might be None or represent the action taken
        )

        # Only way to fix race condition preventing session_service from loading.
        if not self.app._tmpl_attrs.get("runner"):
            self.app.set_up()
        adk_app_name = self.app._tmpl_attrs.get("app_name")
        session_service = self.app._tmpl_attrs.get("session_service")

        session = await session_service.get_session(
            app_name=adk_app_name,
            user_id=user_id,
            session_id=session_id,
        )
        if session:
            self.logger.log_struct(
                {
                    "event_type": "debug_input",
                    "message": f"session {session_id} found: {session}",
                },
                severity="INFO"
            )
        else:
            self.logger.log_struct(
                {
                    "event_type": "debug_input",
                    "message": f"session {session_id} not found",
                },
                severity="INFO"
            )

        await session_service.append_event(session, system_event)

        # Log what we extracted
        self.logger.log_struct(
            {
                "event_type": "extracted_params",
                "session_id": session_id or "no_session",
                "user_id": user_id,
                "message_length": len(message) if message else 0,
                "has_message": bool(message),
                "message_preview": message[:50] if message else "",
                "timestamp": datetime.now(timezone.utc).isoformat(),
            },
            severity="INFO"
        )

        # Validate required parameters
        if not session_id:
            self.logger.log_struct(
                {
                    "event_type": "missing_session_id",
                    "raw_kwargs": str(kw_args),
                    "timestamp": datetime.now(timezone.utc).isoformat(),
                },
                severity="ERROR"
            )
            raise ValueError("session_id is required for stream_query")

        if not message:
            self.logger.log_struct(
                {
                    "event_type": "missing_message",
                    "raw_kwargs": str(kw_args),
                    "timestamp": datetime.now(timezone.utc).isoformat(),
                },
                severity="WARNING"
            )

        # Get or create trace ID for this session
        trace_id = self.get_session_trace(session_id)

        # Log the full user query
        self.logger.log_struct(
            {
                "event_type": "user_query",
                "session_id": session_id,
                "user_id": user_id,
                "user_message": message,
                "timestamp": datetime.now(timezone.utc).isoformat(),
                "invocation_id": f"query-{session_id}-{int(datetime.now(timezone.utc).timestamp())}",
            },
            severity="INFO",
            trace=trace_id,
            labels={
                "session_id": str(session_id),
                "user_id": str(user_id),
                "event_type": "user_query",
            }
        )

        # Track events for this query
        query_events = []
        function_calls = {}

        try:
            # IMPORTANT: ADK expects parameters directly, not under 'input'
            # Based on the error message, stream_query expects 'message' and 'user_id' as direct parameters
            adk_kwargs = {
                "session_id": session_id,
                "user_id": user_id,
                "message": message,
            }

            # Log what we're passing to ADK
            self.logger.log_struct(
                {
                    "event_type": "adk_call",
                    "adk_kwargs": str(adk_kwargs),
                    "timestamp": datetime.now(timezone.utc).isoformat(),
                },
                severity="DEBUG"
            )

            # Run the actual streaming
            for event in self.app.stream_query(**adk_kwargs):
                # Log each streaming event with full details
                if isinstance(event, dict):
                    # Extract key information
                    event_log = {
                        "event_type": "stream_event",
                        "session_id": session_id,
                        "user_id": user_id,
                        "timestamp": event.get("timestamp", datetime.now(timezone.utc).isoformat()),
                        "invocation_id": event.get("invocation_id"),
                        "author": event.get("author"),
                        "event_id": event.get("id"),
                    }

                    # Handle different content types
                    content = event.get("content", {})
                    if content:
                        parts = content.get("parts", [])
                        for part in parts:
                            if "text" in part:
                                # Agent text response
                                event_log["agent_response"] = part["text"]
                                event_log["response_type"] = "text"
                            elif "function_call" in part:
                                # Function call
                                func_call = part["function_call"]
                                event_log["function_call"] = {
                                    "name": func_call.get("name"),
                                    "id": func_call.get("id"),
                                    "args": func_call.get("args")
                                }
                                event_log["response_type"] = "function_call"
                                # Track function calls
                                function_calls[func_call.get("id")] = func_call
                            elif "function_response" in part:
                                # Function response
                                func_resp = part["function_response"]
                                event_log["function_response"] = {
                                    "name": func_resp.get("name"),
                                    "id": func_resp.get("id"),
                                    "response": func_resp.get("response")
                                }
                                event_log["response_type"] = "function_response"

                    # Include usage metadata if present
                    if "usage_metadata" in event:
                        event_log["usage"] = {
                            "prompt_tokens": event["usage_metadata"].get("prompt_token_count"),
                            "completion_tokens": event["usage_metadata"].get("candidates_token_count"),
                            "total_tokens": event["usage_metadata"].get("total_token_count")
                        }

                    # Log the detailed event
                    self.logger.log_struct(
                        event_log,
                        severity="INFO",
                        trace=trace_id,
                        labels={
                            "session_id": str(session_id),
                            "user_id": str(user_id),
                            "event_type": "stream_event",
                            "response_type": event_log.get("response_type", "unknown"),
                            "invocation_id": str(event.get("invocation_id", "")),
                        }
                    )

                    # Add trace_id to response
                    if "metadata" not in event:
                        event["metadata"] = {}
                    event["metadata"]["trace_id"] = trace_id

                    query_events.append(event_log)

                yield event

            # Log query completion with summary
            self.logger.log_struct(
                {
                    "event_type": "query_completed",
                    "session_id": session_id,
                    "user_id": user_id,
                    "user_message": message,
                    "total_events": len(query_events),
                    "function_calls": list(function_calls.values()),
                    "timestamp": datetime.now(timezone.utc).isoformat(),
                },
                severity="INFO",
                trace=trace_id,
                labels={
                    "session_id": str(session_id),
                    "user_id": str(user_id),
                    "event_type": "query_completed",
                }
            )

        except Exception as e:
            # Log detailed error
            self.logger.log_struct(
                {
                    "event_type": "query_error",
                    "session_id": session_id,
                    "user_id": user_id,
                    "user_message": message,
                    "error": str(e),
                    "error_type": type(e).__name__,
                    "timestamp": datetime.now(timezone.utc).isoformat(),
                },
                severity="ERROR",
                trace=trace_id,
                labels={
                    "session_id": str(session_id),
                    "user_id": str(user_id),
                    "event_type": "query_error",
                }
            )
            raise

    def register_operations(self):
        """Register operations for AgentSpace."""
        return {
            "": [
                "get_session",
                "list_sessions",
                "create_session",
                "delete_session",
            ],
            "stream": [
                "streaming_agent_run_with_events",
                "stream_query",
            ],
        }
