# Copyright 2024 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

#
# WARNING: This file is generated by Terraform.  Any direct edits will be overwritten when applying Terraform changes.

#!/bin/bash

export GCP_PROJECT=${project_id}
export GCP_REGION=${location}
export APP_NAMESPACE=${app_namespace}
export APP_NAMESPACE_UNDER=${app_namespace_under}
